### ISSUE TITLE
pip3 install -r requirements.txt  error with gmp.h

### ISSUE THREAD

**Issue by federicocappelli** [singular-labs/Singular-SKAdNetwork-App#18]
I'm trying to configure and run the server but I get this error: `src/curve.h:4:10: fatal error: 'gmp.h' file not found`
I'm using `Python 3.9.6` installed via Brew.

Any suggestion?

```
 skadnetwork-server % pip3 install -r requirements.txt          
Collecting fastecdsa==2.1.2 (from -r requirements.txt (line 1))
  Using cached fastecdsa-2.1.2.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
Collecting Flask==1.1.2 (from -r requirements.txt (line 2))
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Werkzeug>=0.15 (from Flask==1.1.2->-r requirements.txt (line 2))
  Using cached werkzeug-3.0.1-py3-none-any.whl.metadata (4.1 kB)
Collecting Jinja2>=2.10.1 (from Flask==1.1.2->-r requirements.txt (line 2))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting itsdangerous>=0.24 (from Flask==1.1.2->-r requirements.txt (line 2))
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=5.1 (from Flask==1.1.2->-r requirements.txt (line 2))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=2.10.1->Flask==1.1.2->-r requirements.txt (line 2))
  Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.0 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached werkzeug-3.0.1-py3-none-any.whl (226 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl (17 kB)
Building wheels for collected packages: fastecdsa
  Building wheel for fastecdsa (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14-arm64-cpython-311
      creating build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/benchmark.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/util.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/__init__.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/keys.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/curve.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/point.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      copying fastecdsa/ecdsa.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa
      creating build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_point.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_keygen.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_nonce_generation.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_key_recovery.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_whycheproof_vectors.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/__init__.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_brainpool_ecdh.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_rfc6979_ecdsa.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_whitespace_parsing.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_prime_field_curve_math.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      copying fastecdsa/tests/test_p256_ecdsa.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests
      creating build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      copying fastecdsa/encoding/pem.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      copying fastecdsa/encoding/util.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      copying fastecdsa/encoding/__init__.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      copying fastecdsa/encoding/sec1.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      copying fastecdsa/encoding/der.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      copying fastecdsa/encoding/asn1.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/encoding
      creating build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_sec1.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/__init__.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_der.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests/encoding
      copying fastecdsa/tests/encoding/test_asn1.py -> build/lib.macosx-14-arm64-cpython-311/fastecdsa/tests/encoding
      running build_ext
      building 'fastecdsa.curvemath' extension
      creating build/temp.macosx-14-arm64-cpython-311
      creating build/temp.macosx-14-arm64-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -Isrc/ -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/curve.c -o build/temp.macosx-14-arm64-cpython-311/src/curve.o -O2
      In file included from src/curve.c:1:
      src/curve.h:4:10: fatal error: 'gmp.h' file not found
      #include "gmp.h"
               ^~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastecdsa
  Running setup.py clean for fastecdsa
Failed to build fastecdsa
ERROR: Could not build wheels for fastecdsa, which is required to install pyproject.toml-based projects
```

**Comment by federicocappelli** [comment]
Update:

With `CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip3 install -r requirements.txt` I managed to install the requirements but then with `python skadnetwork_server.py` I get:

```
skadnetwork-server % python3 skadnetwork_server.py
Traceback (most recent call last):
  File "/Users/kappe/Developer/Singular-SKAdNetwork-App/skadnetwork-server/skadnetwork_server.py", line 5, in <module>
    from flask import Flask, request, jsonify
  File "/opt/homebrew/lib/python3.11/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/opt/homebrew/lib/python3.11/site-packages/jinja2/__init__.py)
```

**Comment by federicocappelli** [comment]
FYI: I solved configuring a [Python3 virtual environment](https://www.studytonight.com/post/python-virtual-environment-setup-on-mac-osx-easiest-way) and changing the server dependencies to:

```
fastecdsa==2.1.2
flask==3.0.0
jinja2==3.1.2
```
