### ISSUE TITLE
i download the code and i try to run it according to readme. but i got an error when using python3, the reason is that image not fonund, could you help fix it,Thank you

### ISSUE THREAD

**Issue by kevin-ma** [singular-labs/Singular-SKAdNetwork-App#2]
python3 skadnetwork_server.py 
Traceback (most recent call last):
  File "skadnetwork_server.py", line 6, in <module>
    from ecdsa_wrapper import ECDSA
  File "/Users/kevin/Downloads/Singular-SKAdNetwork-App-master/skadnetwork-server/ecdsa_wrapper.py", line 6, in <module>
    from fastecdsa import curve as fe_curve, keys as fe_keys, ecdsa as fe_ecdsa
  File "/Library/Python/3.7/site-packages/fastecdsa/keys.py", line 6, in <module>
    from .ecdsa import verify
  File "/Library/Python/3.7/site-packages/fastecdsa/ecdsa.py", line 5, in <module>
    from fastecdsa import _ecdsa
ImportError: dlopen(/Library/Python/3.7/site-packages/fastecdsa/_ecdsa.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Library/Python/3.7/site-packages/fastecdsa/_ecdsa.cpython-37m-darwin.so
  Reason: image not found

**Comment by danielxt** [comment]
Hi @kevin-ma - did you resolve the issue? if not let us know and we'll take a look at this, otherwise would be great if you can share you solution...

Was it just an installation issue with the fastecdsa package?

Thanks
